Adding admin method to download all users
cto-ai/ops-keycloak pull request #2
Opened 2021-03-06 15:36 UTC by mattcan

The Keycloak endpoint being called is a paged endpoint but there are no headers or response body that informs a user how far they are so I have tried to add that context.

2021-03-06 15:51 UTC, mattcan commented on test/index.test.js
> +  const secondTransaction = kc.allUsers({ accessToken: 'at' }, 1, 1);
```suggestion
  const secondTransaction = kc.allUsers({ accessToken: 'at' }, parsed.next, parsed.limit);
```

2021-03-08 16:18 UTC, davidmarkclements commented on index.js
> +    allUsers: `${url}/admin/realms/${realm}/users`
I think `endpoints.users` is fine - if we need an admin section in future we can just change it and release a major

2021-03-08 16:19 UTC, davidmarkclements commented on index.js
> +  async function allUsers ({ accessToken } = {}, next = 0, limit = 100, filters = {}) {
just `users` is fine (especially since `filters` gives you *not* all users)

2021-03-08 16:20 UTC, davidmarkclements commented on index.js
> +  async function allUsers ({ accessToken } = {}, next = 0, limit = 100, filters = {}) {
make the sig `users(tokens, options)` so `users({ accessToken } = {}, { next = 0, limit = 100, filters = {}})`

2021-03-08 16:34 UTC, davidmarkclements commented on index.js
> +  async function allUsers ({ accessToken } = {}, next = 0, limit = 100, filters = {}) {
if you make this a generator function and change `next` and `limit` to `from` and `to`, you won't have to calculate the returned `next` property or the `limit` property so that they can be passed into the same function call again. 


```js
const result = []
for (const user of users(tokens, {from: 0, to: 1000}) {
  result.push(user)
}
```

or for streaming:


```js
for (const user of users(tokens, {from: 0, to: 1000}) {
  socket.write(JSON.stringify(user))
}
```

or to chunk for any reason:

```js
const iter = users(tokens, {from: 0, to: 1000})
while (await somethingThatHappensLikeUserInputOrNetworkInteraction) {
  sendAChunk(await iter.next())
}
```



The way this can work is with `yield *`:

```js
async function * users ({ accessToken } = {}, { from = 0, to = 100, filters = {}} = {}) {
   cont result = /* do the request etc etc */
   yield * result
   if (result.length < to)  yield * users({ accessToken}, { from: results.length - to, to, filters})
}
```

2021-03-08 16:37 UTC, davidmarkclements commented on readme.md
> +* `tokens` - `accessToken` is required
```suggestion
* `tokens` - `accessToken` with admin privileges **currently not obtainable via this library** is required

```

2021-03-08 16:38 UTC, davidmarkclements commented on index.js
> +    allUsers: `${url}/admin/realms/${realm}/users`
I think what we'll do for getting admin tokens is extend the current signin and signout functions with an admin option, and then just use endpoints.adminLogins - keep the endpoints flat

2021-03-08 16:38 UTC, davidmarkclements requested changes
see comments

2021-03-08 16:42 UTC, davidmarkclements commented on index.js
> +  async function allUsers ({ accessToken } = {}, next = 0, limit = 100, filters = {}) {
this can also be extended if we want to update the from and to at any point

```js
const iter = users(tokens, {from: 0, to: 1000})
const jump = await iter({from: 500, to: 2000})
```

It can be implemented with `returnValue = yield`. This will complicate things though, only do this part if the functionality is necessary

2021-03-08 16:43 UTC, davidmarkclements commented
ideally this PR comes with the ability to login/logout of admin routes as well - if you have capacity

2021-07-08 20:40 UTC, closed without merging